import { FC, ReactNode } from 'react'
import Head from "next/head"

// Props の型を定義します。title は文字列で、children は ReactNode の型（React 要素を表現する任意の型）を持ちます。
type Props = {
    title: string
    children: ReactNode
}

// 引数を受け取る場合、このような書き方をする
// Layout コンポーネントを定義します。Props の型を持つ子コンポーネントとタイトルを受け取ります。
// FC<Props>はFunctional Componentの略で、Reactの関数型コンポーネントを示します。
// Propsはそのコンポーネントが受け取るプロパティの型を指定します。
// つまり、この宣言はLayoutが関数型コンポーネントであり、プロパティとしてchildrenとtitleを受け取ることを示しています。
export const Layout: FC<Props> =({ children, title = 'T3 Stack' }) => {
    return (
        // フラグメント <> で囲まれた JSX を返します。*/}
        <>
        {/* Head コンポーネント（Next.js で提供）を用いて、ページの <head> 部分を定義します。 */}
        <Head>
            {/* <title> タグを使用してページのタイトルを設定します。 */}
            <title>{title}</title>
            {/* <meta> タグを使用してページの説明を設定します。 */}
            <meta name="description" content="Generated by create-t3-app" />
            {/* <link> タグを使用して favicon を設定します。 */}
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <main> タグを使用してメインコンテンツ部分を定義します。子コンポーネント（{children}）がここに挿入されます。 */}
        <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
            {children}
        </main>
        </>
    )
}
